### ISSUE TITLE
tokio::main unexpectedly selects basic_scheduler

### ISSUE THREAD

**Issue by gedkins** [tokio-rs/tokio#1992]
##  Version

Version 0.2.5

tokio v0.2.5
tokio-macros v0.2.1

## Platform

Darwin *** 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64

## Subcrates

tokio-macros

## Description

1. I tried using tokio with the new scheduler (version >= 0.2.0) with `#[tokio::main(threaded_scheduler)]` around the async main function. "rt-threaded" was not listed in the feature flags in my Cargo.toml

Expected behaviour: either the threaded scheduler is used or the compiler issues an error.

Actual behaviour: the basic_scheduler is used

2. Using `[tokio::main]` (without explicitly specifying a scheduler) will also select the basic_scheduler unless the rt-threaded feature flag is specified. This is contrary to the documentation for tokio::main.

## Relevant code
https://github.com/tokio-rs/tokio/blob/master/tokio-macros/src/lib.rs

```
    let result = match runtime {
        Runtime::Threaded | Runtime::Auto => quote! {
            #(#attrs)*
            #vis fn #name(#inputs) #ret {
                tokio::runtime::Runtime::new().unwrap().block_on(async { #body })
            }
        },
        Runtime::Basic => quote! {
            #(#attrs)*
            #vis fn #name(#inputs) #ret {
                tokio::runtime::Builder::new()
                    .basic_scheduler()
                    .enable_all()
                    .build()
                    .unwrap()
                    .block_on(async { #body })
            }
        },
    };
```

If the Threaded runtime is selected in the macro, it will construct a Runtime::new(). As specified in the Runtime documentation,

> if only the rt-core feature is enabled, the basic scheduler is used instead

This is definitely contrary to what I'd expect.

Probably the expected behaviour would be to issue an error if threaded_scheduler is explicitly specified and a warning if no scheduler is specified and it has to fall back to basic_scheduler?

## Note

Prior to version 0.2.0, the (old) threaded scheduler was used by default as the feature flags didn't exist. This means that people upgrading to >=0.2.0 may see performance degradation if they're not aware of this issue, as the basic_scheduler generally performs worse on multi-core systems.

**Comment by vorot93** [comment]
This is probably fixed in 0.2.8.

**Comment by gedkins** [comment]
I'm not sure it's fixed - I'm still seeing this behaviour on version 0.2.8:

| features    | macro                                | behaviour          |       |
| ------------|--------------------------------------|--------------------|------ |
|             | `#[tokio::main]`                     | basic scheduler    | ok    |
|             | `#[tokio::main(basic_scheduler)]`    | basic scheduler    | ok    |
|             | `#[tokio::main(threaded_scheduler)]` | basic scheduler    | wrong |
| rt-threaded | `#[tokio::main]`                     | threaded scheduler | ok    |
| rt-threaded | `#[tokio::main(basic_scheduler)]`    | basic scheduler    | ok    |
| rt-threaded | `#[tokio::main(threaded_scheduler)]` | threaded scheduler | ok    |

The case I've marked "wrong", where the threaded_scheduler is requested but not supported by the feature flags, should probably cause a compile time error.

Additionally the [documentation](https://docs.rs/tokio/0.2.8/tokio/attr.main.html) is confusing: it says it's supported on feature="rt-threaded" only, which isn't true, and no longer mentions the basic_scheduler and threaded_scheduler options.

**Comment by Darksonn** [comment]
Closing in favor of #2698.
